namespace KnowledgebaseVectoriser.Services.Generation
{
    /// <summary>
    /// Templates for generating .agent files, .skills, and .instructions
    /// </summary>
    public static class GenerationTemplates
    {
        /// <summary>
        /// Template for .agent files with architectural context
        /// </summary>
        public static string AgentFileTemplate = """
            # {AGENT_NAME}
            
            {AGENT_DESCRIPTION}
            
            ## Architectural Context
            
            This agent is informed by the following architectural decisions and guidelines:
            
            {ARCHITECTURAL_CONTEXT}
            
            ## Related Architecture Decision Records (ADRs)
            
            {RELATED_ADRS}
            
            ## Guidelines to Follow
            
            {GUIDELINES}
            
            ## Code Examples and Patterns
            
            {CODE_EXAMPLES}
            
            ## Instructions
            
            When working on this project, ensure you:
            
            {INSTRUCTIONS}
            
            ---
            *Generated by Architect Central based on current architecture documentation*
            """;

        /// <summary>
        /// Template for .skills files
        /// </summary>
        public static string SkillFileTemplate = """
            # {SKILL_NAME}
            
            {SKILL_DESCRIPTION}
            
            ## Capability
            
            {CAPABILITY_DESCRIPTION}
            
            ## Implementation Guidance
            
            {IMPLEMENTATION_GUIDANCE}
            
            ## Related ADRs
            
            {RELATED_ADRS}
            
            ## Example Usage
            
            {USAGE_EXAMPLES}
            
            ---
            *Generated by Architect Central*
            """;

        /// <summary>
        /// Template for .instructions files
        /// </summary>
        public static string InstructionFileTemplate = """
            # {INSTRUCTION_TITLE}
            
            ## Purpose
            
            {PURPOSE}
            
            ## Architectural Standards
            
            {ARCHITECTURAL_STANDARDS}
            
            ## Code Patterns
            
            {CODE_PATTERNS}
            
            ## Best Practices
            
            {BEST_PRACTICES}
            
            ## Anti-Patterns to Avoid
            
            {ANTI_PATTERNS}
            
            ## References
            
            {REFERENCES}
            
            ---
            *Based on ADRs: {ADR_LIST}*
            *Generated: {GENERATION_DATE}*
            """;

        /// <summary>
        /// Template for ADR summary in generated content
        /// </summary>
        public static string ADRSummaryTemplate = """
            ### {ADR_TITLE} (ADR-{ADR_NUMBER})
            **Status**: {STATUS}
            
            **Decision**: {DECISION_SUMMARY}
            
            **Key Points**:
            {KEY_POINTS}
            """;

        /// <summary>
        /// Template for guideline summary
        /// </summary>
        public static string GuidelineSummaryTemplate = """
            ### {GUIDELINE_TITLE}
            
            {GUIDELINE_SUMMARY}
            
            **Key Recommendations**:
            {KEY_RECOMMENDATIONS}
            """;
    }
}
